import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "포트폴리오",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <script src="http://unpkg.com/tone"></script>
        <div className="bg-white min-h-[500px] mx-[60px] mt-[60px] mb-[120px] py-10 px-[55px]">
          {children}
        </div>
      </body>
    </html>
  );
}
